site_name: PygameVN
repo_url: https://github.com/staFF6773/PygameVN
  
theme:
  name: material
  features:
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

nav:
  - Home: index.md
  - Galery: Galery.md
  - Introduction to Pygame: introduction_pygame.md
  - Setting Up the Environment: setting_up_environment.md
  - Basic Structure of a Visual Novel: basic_structure.md
  - Displaying Images and Backgrounds: displaying_images_backgrounds.md
  - Displaying Text and Dialogues: displaying_text_dialogues.md
  - Handling Choices and Decisions: handling_choices_decisions.md
  - Game State Management: game_state_management.md
  - Music and Sound Effects: music_sound_effects.md
  - Basic Animations: basic_animations.md
  - Save and Load System: save_load_system.md
  - Optimization and Best Practices: optimization_best_practices.md

copyright: Copyright &copy; 2024 <a href="https://github.com/staFF6773/PygameVN" target="_black" rel="noopener">PygameVN</a>
